config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
  root to: 'home#index'

  post '/auth/:provider/callback', to: 'sessions#create'
  delete '/log_out', to: 'sessions#destroy', as: :log_out
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  def self.from_omniauth(auth)
    info = auth['info']
    user = find_or_create_by(uid: get_uid(info['urls']['Profile']))

    user.nickname = info['nickname']
    user.avatar_url = info['image']
    user.profile_url = info['urls']['Profile']
    user.save!
    user
  end

  def self.get_uid(profile_url)
    profile_url.split('/').last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    return nil unless session[:user_id]
    @current_user ||= User.find_by(id: session[:user_id])
  end

  helper_method :current_user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :verify_authenticity_token, only: :create

  def create
    begin
      @user = User.from_omniauth(request.env['omniauth.auth'])
    rescue
      flash[:error] = 'Cannot authorize you...'
    else
      session[:user_id] = @user.id
      flash[:success] = "Welcome, #{@user.nickname}!"
    end

    redirect_to root_path
  end

  def destroy
    if current_user
      session.delete(:user_id)
      flash[:success] = 'Goodbye!'
    end

    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<% if current_user %>
  <div class="clear-fix">
    <ul class="nav navbar-nav pull-right">
      <li><%= image_tag current_user.avatar_url, alt: current_user.nickname %></li>
      <li><%= link_to 'Log Out', log_out_path, method: :delete %></li>
    </ul>
  </div>
<% else %>
  <ul class="nav navbar-nav">
    <li><%= link_to 'Log In via Steam', '/auth/steam' %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SteamChat</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="center-wrapper">


      <%= render 'shared/flash_messages' %>
      <%= yield %>


    </div>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% if flash.any? %>
  <% flash.each do |type, message| %>
    <%= content_tag(:div, message, class: "flash flash-#{type}") %>
  <% end %>
<% end %>